// <auto-generated />
namespace Supreme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DeliveryNote_addOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeliveryNote_addOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "201609071343390_DeliveryNote_addOrders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
